package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"fmt"
	"os"
	"time"

	"github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	"github.com/oleorhagen/golf-graphql/graph/model"
)

// CreatePlayer is the resolver for the createPlayer field.
func (r *mutationResolver) CreatePlayer(ctx context.Context, input model.NewPlayer) (*model.Player, error) {
	player := &model.Player{
		Name: input.Name,
	}

	r.players = append(r.players, player)
	return player, nil
}

// Players is the resolver for the players field.
func (r *queryResolver) Players(ctx context.Context) ([]*model.Player, error) {
	var names []*model.Player
	var n string
	rows, err := r.DB.Query(ctx, "select name from player")
	_, err = pgx.ForEachRow(rows, []any{&n}, func() error {
		names = append(names, &model.Player{Name: n})
		return nil
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "QueryRow failed: %v\n", err)
		return nil, fmt.Errorf("Failed to query the database for players: %w", err)
	}

	r.players = names
	return r.players, nil
}

// Tournaments is the resolver for the tournaments field.
func (r *queryResolver) Tournaments(ctx context.Context) ([]*model.Tournament, error) {
	var names []*model.Tournament
	var id uuid.UUID
	var name string
	var year time.Time
	rows, err := r.DB.Query(ctx, "select id, name, year from tournament")
	_, err = pgx.ForEachRow(rows, []any{&id, &name, &year}, func() error {
		fmt.Fprintf(os.Stderr, "Got: %v", id)
		names = append(names, &model.Tournament{ID: id, Name: name, Year: year})
		return nil
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "QueryRow failed: %v\n", err)
		return nil, fmt.Errorf("Failed to query the database for tournaments: %w", err)
	}

	r.tournaments = append(r.tournaments, names...)
	return r.tournaments, nil
}

// Scorecards is the resolver for the scorecards field.
func (r *queryResolver) Scorecards(ctx context.Context) ([]*model.Scorecard, error) {
	var scorecards []*model.Scorecard
	var id uuid.UUID
	var tournamentID uuid.UUID
	var playerID uuid.UUID
	var handicap int32
	var course_name string
	// var player model.Player // TODO - Required for the Graph
	rows, err := r.DB.Query(ctx,
		"select id, tournament_id, scorer_id, handicap, course_name from scorecard",
	)
	_, err = pgx.ForEachRow(rows, []any{&id, &tournamentID, &playerID, &handicap, &course_name}, func() error {
		fmt.Fprintf(os.Stderr, "Got: %v\n", id)
		scorecards = append(scorecards, &model.Scorecard{
			ID:           id,
			TournamentID: tournamentID,
			Handicap:     handicap,
			CourseName:   course_name,
			// Player - TODO
		})
		return nil
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "QueryRow failed: %v\n", err)
		return nil, fmt.Errorf("Failed to query the database for scorecards: %w", err)
	}

	r.scorecards = append(r.scorecards, scorecards...)
	return r.scorecards, nil
}

// Player is the resolver for the player field.
func (r *scorecardResolver) Player(ctx context.Context, obj *model.Scorecard) (*model.Player, error) {
	var names []*model.Player
	var n string
	rows, err := r.DB.Query(ctx, "select name from player")
	_, err = pgx.ForEachRow(rows, []any{&n}, func() error {
		names = append(names, &model.Player{Name: n})
		return nil
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "QueryRow failed: %v\n", err)
		return nil, fmt.Errorf("Failed to query the database for players: %w", err)
	}

	r.players = names
	return r.players, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Scorecard returns ScorecardResolver implementation.
func (r *Resolver) Scorecard() ScorecardResolver { return &scorecardResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type scorecardResolver struct{ *Resolver }
