package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"fmt"
	"os"
	"time"

	"github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	"github.com/oleorhagen/golf-graphql/graph"
	"github.com/oleorhagen/golf-graphql/graph/model"
)

// Holes is the resolver for the holes field.
func (r *courseResolver) Holes(ctx context.Context, obj *model.Course) ([]*model.Hole, error) {
	var hole_nr int32
	var index int32
	var par int32
	rows, err := r.DB.Query(ctx, "select hole_nr, hole_index, par from course_hole where course_name=$1", obj.Name)
	if err != nil {
		return nil, fmt.Errorf("Failed to query the database for players (%s): %w", obj.Name, err)
	}
	var holes []*model.Hole
	_, err = pgx.ForEachRow(rows, []any{&hole_nr, &index, &par}, func() error {
		holes = append(holes, &model.Hole{
			Nr:    hole_nr,
			Index: index,
			Par:   par,
		})
		return nil
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "QueryRow failed: %v\n", err)
		return nil, fmt.Errorf("Failed to query the database for holes: %w", err)
	}

	return holes, nil
}

// CreatePlayer is the resolver for the createPlayer field.
func (r *mutationResolver) CreatePlayer(ctx context.Context, input model.NewPlayer) (*model.Player, error) {
	player := &model.Player{
		Name: input.Name,
	}

	return player, nil
}

// Scorecards is the resolver for the scorecards field.
func (r *playerResolver) Scorecards(ctx context.Context, obj *model.Player) ([]*model.Scorecard, error) {
	scorecards, err := getScorecards(r, ctx, obj.ID)
	if err != nil {
		fmt.Fprintf(os.Stderr, "QueryRow failed: %v\n", err)
		return nil, fmt.Errorf("Failed to query the database for players scorecards: %w", err)
	}

	fmt.Fprintf(os.Stderr, "Scorecards player results: %v", scorecards)
	return scorecards, nil
}

// Players is the resolver for the players field.
func (r *queryResolver) Players(ctx context.Context) ([]*model.Player, error) {
	var players []*model.Player
	var id uuid.UUID
	var n string
	var handicap int32
	rows, err := r.DB.Query(ctx, "select id, name, handicap from scorer")
	_, err = pgx.ForEachRow(rows, []any{&id, &n, &handicap}, func() error {
		players = append(players, &model.Player{ID: id, Name: n, Handicap: handicap})
		return nil
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "QueryRow failed: %v\n", err)
		return nil, fmt.Errorf("Failed to query the database for players: %w", err)
	}

	return players, nil
}

// Teams is the resolver for the teams field.
func (r *queryResolver) Teams(ctx context.Context) ([]*model.Team, error) {
	var teams []*model.Team
	var id uuid.UUID
	var n string
	var handicap int32
	rows, err := r.DB.Query(ctx, "select id, name, handicap from team")
	_, err = pgx.ForEachRow(rows, []any{&id, &n, &handicap}, func() error {
		teams = append(teams, &model.Team{ID: id, Name: n, Handicap: handicap})
		return nil
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "QueryRow failed: %v\n", err)
		return nil, fmt.Errorf("Failed to query the database for teams: %w", err)
	}

	return teams, nil
}

// Scorecards is the resolver for the scorecards field.
func (r *queryResolver) Scorecards(ctx context.Context) ([]*model.Scorecard, error) {
	var scorecards []*model.Scorecard
	var id uuid.UUID
	var tournamentID uuid.UUID
	var playerID uuid.UUID
	var handicap int32
	var course_name string
	rows, err := r.DB.Query(ctx,
		"select id, tournament_id, scorer_id, handicap, course_name from scorecard",
	)
	_, err = pgx.ForEachRow(rows, []any{&id, &tournamentID, &playerID, &handicap, &course_name}, func() error {
		fmt.Fprintf(os.Stderr, "Got: %v\n", id)
		scorecards = append(scorecards, &model.Scorecard{
			ID:           id,
			TournamentID: tournamentID,
			Handicap:     handicap,
			CourseName:   course_name,
			PlayerID:     playerID,
		})
		return nil
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "QueryRow failed: %v\n", err)
		return nil, fmt.Errorf("Failed to query the database for scorecards: %w", err)
	}

	return scorecards, nil
}

// Courses is the resolver for the courses field.
func (r *queryResolver) Courses(ctx context.Context) ([]*model.Course, error) {
	var courses []*model.Course
	var name string
	var slope int32
	var course_rating float64
	var nr_holes int32
	rows, err := r.DB.Query(ctx, "select name, slope, course_rating, nr_holes from course")
	_, err = pgx.ForEachRow(rows, []any{&name, &slope, &course_rating, &nr_holes}, func() error {
		courses = append(courses, &model.Course{Name: name, Slope: slope, CourseRating: course_rating, NrHoles: nr_holes})
		return nil
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "QueryRow failed: %v\n", err)
		return nil, fmt.Errorf("Failed to query the database for courses: %w", err)
	}

	return courses, nil
}

// Tournaments is the resolver for the tournaments field.
func (r *queryResolver) Tournaments(ctx context.Context) ([]*model.Tournament, error) {
	var tournaments []*model.Tournament
	var id uuid.UUID
	var name string
	var year time.Time
	rows, err := r.DB.Query(ctx, "select id, name, year from tournament")
	_, err = pgx.ForEachRow(rows, []any{&id, &name, &year}, func() error {
		fmt.Fprintf(os.Stderr, "Got: %v", id)
		tournaments = append(tournaments, &model.Tournament{ID: id, Name: name, Year: year})
		return nil
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "QueryRow failed: %v\n", err)
		return nil, fmt.Errorf("Failed to query the database for tournaments: %w", err)
	}

	return tournaments, nil
}

// Player is the resolver for the player field.
func (r *scorecardResolver) Player(ctx context.Context, obj *model.Scorecard) (*model.Player, error) {
	var id uuid.UUID
	var name string
	var handicap int32
	err := r.DB.QueryRow(ctx, "select id, name, handicap from scorer where id=$1", obj.PlayerID).Scan(&id, &name, &handicap)
	if err != nil {
		fmt.Fprintf(os.Stderr, "QueryRow failed (%s): %v\n", obj.PlayerID, err)
		return nil, fmt.Errorf("Failed to query the database for players (%s): %w", obj.PlayerID, err)
	}
	player := model.Player{
		ID:       id,
		Name:     name,
		Handicap: handicap,
	}

	return &player, nil
}

// Course returns graph.CourseResolver implementation.
func (r *Resolver) Course() graph.CourseResolver { return &courseResolver{r} }

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Player returns graph.PlayerResolver implementation.
func (r *Resolver) Player() graph.PlayerResolver { return &playerResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

// Scorecard returns graph.ScorecardResolver implementation.
func (r *Resolver) Scorecard() graph.ScorecardResolver { return &scorecardResolver{r} }

type courseResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type playerResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type scorecardResolver struct{ *Resolver }
