// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
)

type Course struct {
	Name  string  `json:"name"`
	Holes []*Hole `json:"holes,omitempty"`
}

type Hole struct {
	Nr int32 `json:"nr"`
}

type Mutation struct {
}

type NewPlayer struct {
	Name string `json:"name"`
}

type Player struct {
	ID         uuid.UUID    `json:"id"`
	Name       string       `json:"name"`
	Handicap   int32        `json:"handicap"`
	Scorecards []*Scorecard `json:"scorecards,omitempty"`
}

type Query struct {
}

type Tournament struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Year time.Time `json:"year"`
}
