// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
)

type Course struct {
	Name  string  `json:"name"`
	Holes []*Hole `json:"holes,omitempty"`
}

type Hole struct {
	Nr int32 `json:"nr"`
}

type Mutation struct {
}

type NewPlayer struct {
	Name string `json:"name"`
}

type Player struct {
	Name       string       `json:"name"`
	Scorecards []*Scorecard `json:"scorecards,omitempty"`
}

type Query struct {
}

type Scorecard struct {
	ID           uuid.UUID `json:"id"`
	TournamentID uuid.UUID `json:"tournament_id"`
	Handicap     int32     `json:"handicap"`
	CourseName   string    `json:"course_name"`
	Player       *Player   `json:"player"`
}

type Tournament struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Year time.Time `json:"year"`
}
