// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Course struct {
	Name  string  `json:"name"`
	Holes []*Hole `json:"holes,omitempty"`
}

type Hole struct {
	Nr int32 `json:"nr"`
}

type Player struct {
	Name       string       `json:"name"`
	Scorecards []*Scorecard `json:"scorecards,omitempty"`
}

type Query struct {
}

type Scorecard struct {
	ID     string  `json:"id"`
	Player *Player `json:"player"`
}

type Tournament struct {
	Name   string  `json:"name"`
	Player *Player `json:"player"`
}
